# Generated by Django 4.0.6 on 2022-10-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_remove_stock_itemcreation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier', models.CharField(max_length=225)),
                ('mailing_name', models.CharField(max_length=225)),
                ('address', models.TextField(max_length=225)),
                ('State', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='receipt_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_note_no', models.IntegerField()),
                ('Receipt_doc_no', models.IntegerField()),
                ('disp_thro', models.CharField(max_length=225)),
                ('destination', models.CharField(max_length=225)),
                ('carrier_name', models.CharField(max_length=225)),
                ('Lading_bill_no', models.IntegerField()),
                ('date', models.DateField()),
                ('motor_veh_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voucher_sales',
            fields=[
                ('vou_type', models.CharField(default=False, max_length=225)),
                ('sal_no', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('Cur_bal', models.IntegerField(default=True)),
                ('salesledger', models.CharField(max_length=225)),
                ('Cur_bal1', models.IntegerField(default=True)),
                ('quantity', models.IntegerField(default=True)),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('itemname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item')),
                ('party_AC_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='voucher_purchase',
            fields=[
                ('vou_type1', models.CharField(default=True, max_length=225)),
                ('pur_no', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('invoiceno', models.IntegerField()),
                ('date', models.DateField(default=True)),
                ('Cur_bal', models.IntegerField(default=True)),
                ('purchaseledger', models.CharField(max_length=225)),
                ('Cur_bal1', models.IntegerField(default=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('itemname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item')),
                ('party_AC_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='stock_item_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('godown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.creategodown')),
            ],
        ),
    ]
