# Generated by Django 4.0.6 on 2022-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_party_details_receipt_details_voucher_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_purchase',
            name='narration',
            field=models.CharField(default=True, max_length=225),
        ),
    ]
