# Generated by Django 4.0.6 on 2022-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_voucher_purchase_narration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_item_allocation',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='stock_item_allocation',
            name='godown',
            field=models.CharField(default=True, max_length=225),
        ),
    ]
