# Generated by Django 4.0.6 on 2022-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_voucher_purchase_party_ac_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_purchase',
            name='itemname',
            field=models.CharField(default=True, max_length=225),
        ),
    ]
