# Generated by Django 4.0.6 on 2022-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_alter_voucher_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_allocation',
            name='godown',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='voucher_purchase',
            name='vou_type1',
            field=models.CharField(default=False, max_length=225),
        ),
    ]
