# Generated by Django 4.0.6 on 2022-10-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_alter_stock_item_allocation_godown_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock_item_allocation',
            new_name='stock_item_allocat',
        ),
    ]
