# Generated by Django 4.0.6 on 2022-10-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_rename_stock_item_allocation_stock_item_allocat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_allocat',
            name='godown',
            field=models.CharField(default=False, max_length=225),
        ),
    ]
