# Generated by Django 4.0.6 on 2022-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_remove_creategodown_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_purchase',
            name='amount1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voucher_purchase',
            name='itemname1',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AddField(
            model_name='voucher_purchase',
            name='quantity1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voucher_purchase',
            name='rate1',
            field=models.IntegerField(null=True),
        ),
    ]
