# Generated by Django 4.0.6 on 2022-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_voucher_purchase_amount1_voucher_purchase_itemname1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher_sales',
            old_name='vou_type',
            new_name='vou_type1',
        ),
        migrations.AddField(
            model_name='voucher_sales',
            name='amount1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voucher_sales',
            name='itemname1',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AddField(
            model_name='voucher_sales',
            name='narration',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AddField(
            model_name='voucher_sales',
            name='quantity1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voucher_sales',
            name='rate1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voucher_sales',
            name='itemname',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='voucher_sales',
            name='party_AC_name',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='voucher_sales',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
