# Generated by Django 4.0.6 on 2022-10-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_vouchers_debit_note_delete_debit_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers_debit_note',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='vouchers_debit_note',
            name='itemname1',
        ),
        migrations.RemoveField(
            model_name='vouchers_debit_note',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='vouchers_debit_note',
            name='rate1',
        ),
    ]
